### ISSUE TITLE
Handling of symlinks in Windows environments

### ISSUE THREAD

**Issue by bechte** [sap-commerce-tools/ccv2-project-template#13]
We are happy to test the project template and we like the combination of having the sap gradle plugin built in here to do much of the magic.

Still, in mixed developer environments (Unix, Mac, Windows), one struggles with this approach due to the use of symlinks within the local-config folder.

I also found a well documented problem description at stackoverflow, so I will refer to it, rather then writing everything down once again:
https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

My proposal to "fix" this issue would be, to add the linking functionality to the gradle plugin and add the local-config folder completely to the .gitignore list. This way, the gradle plugin could ensure that the symbolic links are created correctly depending on the underlying operating system.

Any thoughts to it?

**Comment by mpern** [comment]
I will be honest, it has been a while since I've done some real dev work on Windows.

That said, the symlink situation should be solved with Windows 10's "Developer Mode" plus the necessary git config to allow symlinks on Windows.

https://stackoverflow.com/a/59761201

P.S.:
Back in the day, I used to develop Commerce in a beefy Linux VM. (Important: Do everything in the VM. Do not put the poject in a shared folder)
You will be surprised how much faster it builds.

**Comment by bechte** [comment]
I wouldnt develop on Windows myself, neither, but there are ppl out there that rely on Windows due to company policies. And I also heard that some of them wont be able to activate dev mode or install VMs.

That said, do you see chances that we could come around with a different solution that generates the properties for local development on the fly by calling a build script? I think it would be worth it. 😊

**Comment by mpern** [comment]
I will definitely think about it.

> functionality to the gradle plugin and add the local-config folder completely to the .gitignore list. This way, the gradle plugin could ensure that the symbolic links are created correctly depending on the underlying operating system.

Can devs on Windows without Developer Mode live with the requirement of an elevated prompt for that step? 🤔

**Comment by bechte** [comment]
I think so. Typically, symlinks are not created all the time, but rather used like in this context and remain almost stable. Therefore, I think it would be ok, but I have no experience with this on Windows. I will ask a team mate to perform the following tests before we proceed:

1. Install a newer system wide git client and ticking the setup option "allow symlinks" and see if that works around the issue
2. Use an newer source tree client
3. Write a test build script for gradle that creates a couple of symlinks to verify what happens if executed with or without UAC.

I'll get back with the results.

**Comment by mpern** [comment]
Another option I forgot to mention yesterday:
Use WSL2!
Based in feedback from colleagues, it works amazingly well.

**Comment by bechte** [comment]
So we have tested the following method and think this is ok, for the time being:

1. Install a newer GIT client on Windows ticking the option to "allow symlinks"
2. Clone the repository using administrative rights (or developer mode to circumstance UAT checks) for the GIT Bash (or whatever tool you use)

The links will be created correctly and as they are only created once, do not change frequently, and the right is only needed on creating, this workaround solves our issue.

I, therefore, close this issue. Thank you, @mpern, for sharing thoughts on that.
